const data = {
  products: [
    {
      name: 'New Apple iPhone 13 Pro Max 512 GB Blue',
      slug: 'Iphone-13-promax',
      category: 'Smartphones',
      image: '/images/one.jpg',
      price: 1085.61,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Near new condition',
    },
    {
      name: 'New Samsung Galaxy A13 64 GB Bronze',
      slug: 'samsung-galaxy-a13',
      category: 'Smartphones',
      image: '/images/two.jpg',
      price: 67.45,
      countInStock: 0,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 10,
      description: 'Condition: New',
    },
    {
      name: 'LG Wing 5G 128 GB Black',
      slug: 'lg-wing-5g',
      category: 'Smartphones',
      image: '/images/three.jpg',
      price: 395,
      countInStock: 16,
      brand: 'Lg',
      rating: 4.5,
      numReviews: 10,
      description: 'Condition: New',
    },
    {
      name: 'Huawei Mate 20 128 GB for Sale',
      slug: 'huawei-mate-40',
      category: 'Smartphones',
      image: '/images/four.jpg',
      price: 395,
      countInStock: 16,
      brand: 'Huawei',
      rating: 4.5,
      numReviews: 10,
      description: 'Used Condition',
    },
  ],
};

export default data;
